### ISSUE TITLE
Why is ewoms using it's parallelization approach and does not reuse existing ones?

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#107]
When I read through #106 I was surprised to see all those manual fiddling with low level MPI code. Would it not have been easier to reuse what is there in and expected by dune-istl/dune-grid? While certainly not bug free (what code is?) I would assume that it might have been tested by a wider audience than ewoms. And (here I might be subjective as one of the authors of DUNE) the stuff in DUNE seems to have cleaner interfaces, too.

BTW this is approach is specific to ewoms and not in upstream DUMUX, right?

**Comment by andlaus** [comment]
> Would it not have been easier to reuse what is there in and expected by dune-istl/dune-grid?

yes and no -- there are several reasons why eWoms rolls its our own stuff:

- I'm not aware of any unstructured Dune grids that support arbitrary overlaps. Since this is essential to get good convergence for some problems and porous media problems tend to use unstructured grids extensively, the eWoms infrastructure fiddles around this by implementing algebraic overlaps. (that code is a beast!)
- As far as I can see, the MPI infrastructure of dune-grid is very targeted for grid communication. This makes it quite unsuitable for dealing with something like algebraic overlaps where some data is not necessarily associated with any grid entity seen by the local process. (Note that since the Dune MPI code is somewhat opaque to me, this it might not actually be the case.)
- using MPI directly is potentially faster because no abstraction layer obfuscates the cost of the operations.

> I would assume that it might have been tested by a wider audience than ewoms.

I'd certainly think that wider testing would be a very good thing, but so far nobody was interested in this code. (this was not helped by the fact that I haven't been actively advertising  that functionality.)

> the stuff in DUNE seems to have cleaner interfaces, too.

that's true, but unfortunately it only supports grid-based communication.

> BTW this is approach is specific to ewoms and not in upstream DUMUX, right?

almost correct: until about a year ago Dumux shipped a old buggy version of this code. (they removed it since, I suppose they weren't able to maintain it.)

**Comment by andlaus** [comment]
can the issue be closed?

**Comment by andlaus** [comment]
I guess this question has been sufficiently answered. If you disagree, please re-open.
