### ISSUE TITLE
ebos uses different transmissibilties for loadbalancing than legacy.

### ISSUE THREAD

**Issue by blattms** [OPM/ewoms#136]
ewoms/ebos uses the unprocessed transmissibilities from eclipse for loadbalancing while legacy uses those stored inside of the Geology (they seem to be something different).

**Comment by andlaus** [comment]
do you mean [here](https://github.com/OPM/ewoms/blob/master/ebos/eclcpgridmanager.hh#L142)? If I'm not *really* mistaken, it uses the same transmissibilities as the main simulator, i.e. the ones produced by [`EclTransmissibility`](https://github.com/OPM/ewoms/blob/master/ebos/ecltransmissibility.hh#L99). bugs are possible, of course...

**Comment by andlaus** [comment]
BTW: I've got trouble testing this because I could not make ZOLTAN work...

**Comment by blattms** [comment]
Well, this is a reminder that there might something wrong, for me. We need to keep track somehow and somebody said there was a difference sometime. That must not hold today, though.

**Comment by blattms** [comment]
@andlaus They seem to be calculated independent of whether ZOLTAN is there or not as long as you are using more than one process. We can just write them to file and compare with e.g. meld.

**Comment by andlaus** [comment]
> @andlaus They seem to be calculated independent of whether ZOLTAN is there or not as long as you are using more than one process. We can just write them to file and compare with e.g. meld.

sure, but it seems like the partitioning process ignores edge weights if zoltan is not installed. Last time I tried this on norne, the `faceTrans` argument did not make a difference?!

**Comment by andlaus** [comment]
I guess I have to slightly correct myself; it makes a small difference: for Norne with four processes the grid partition with most elements goes from 21253 to 21259 elements, while the partition with the least elements stays at 4413 elements (i.e., the ratio is roughly 5:1). That said, maybe the transmissibilities are indeed wrong.

**Comment by andlaus** [comment]
Ok, i've verified that the transmissibilities which are passed to `loadBalance()` are identical to the ones which are used for linearization in sequential mode. This implies that they are correct unless something is seriously wrong with all our testing up to now?

**Comment by andlaus** [comment]
BTW: I think these small differences in the number of cells could be caused by the fact that wells are considered in the load balancing code if the EclipseState and transmissibilities are passed, while a plain call to `grid.loadBalance()` probably ignores them. this would support the original theory that the transmissibilities are ignored by `CpGrid` if ZOLTAN is not available.

are you looking into this @blattms?

**Comment by atgeirr** [comment]
@andlaus in order to make any reasonable parallel runs on the real cases I believe Zoltan is absolutely necessary. If you cannot set it up on your system's native distro, consider using an Ubuntu VM for development of this since there you would be able to simply follow the website instructions and install all necessary packages, including Zoltan.

**Comment by andlaus** [comment]
> in order to make any reasonable parallel runs on the real cases I believe Zoltan is absolutely necessary

I've come to the same conclusion. Since this is quite non-obvious, I'm wondering whether it is not better to make the `loadBalance()` throw an exception if ZOLTAN is not available.

> If you cannot set it up on your system's native distro, consider using an Ubuntu VM for development

I'm pretty confident that I'll manage to set up ZOLTAN if I spend enough energy on it, but so far I was not aware that this was necessary. Also, can ZOLTAN be provided via the default mechanisms in principle? (i.e., the debian/fedora/openSUSE package archives.) If not, wouldn't this be a reason to add support for a graph partitioner with better availability like [SCOTCH](https://www.labri.fr/perso/pelegrin/scotch/)?

**Comment by blattms** [comment]
The famous history. Someone throw ZOLTAN into the discussion as it supports several other partitioners and some modern agorithm.

BTW https://en.opensuse.org/openSUSE:Science_Math suggests that there is Trilinos in Suse. Zoltan is part of Trilinos and should/could be included.

Yes it is very non-obvious that Zoltan should be installed.

**Comment by andlaus** [comment]
ok, I've figured that there already is a zoltan package in ubuntu (that makes me wonder why the zoltan people hide the download behind a registration form): libtrilinos-zoltan-dev. any idea what's the difference to the libtrilinos-zoltan2-dev package?

**Comment by andlaus** [comment]
> The famous history. Someone throw ZOLTAN into the discussion as it supports several other partitioners and some modern agorithm.

yeah, people like me never get it right the first time ;)

**Comment by atgeirr** [comment]
> Yes it is very non-obvious that Zoltan should be installed.

We have recently fixed the website docs about this though.

> any idea what's the difference to the libtrilinos-zoltan2-dev package?

No, but the (verified by Arne Morten) install instructions on the web site do not include the "2".

**Comment by andlaus** [comment]
> We have recently fixed the website docs about this though.

could we make this fool-proof?

**Comment by andlaus** [comment]
ok. I've run the load balancing with zoltan installed and the fewest-to-most-elements-parition-ratio goes down to 1:1.5 for Norne. While that's not exactly good IMO, it's still much better...

**Comment by andlaus** [comment]
this has been fixed as far as I know.
